init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed
  
# Install scripts. (runs after repo cloning)
install:
  - cmd: cd tools
  - ps: (new-object net.webclient).DownloadFile('https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_windows_amd64.zip', "$pwd\consul.zip")
  - cmd: 7z e consul.zip
  - cmd: for /F %%A in ('consul agent -dev -bind 127.0.0.1 -config-file=server.json') do set PID=%%A
  - cmd: timeout /t 120
  - cmd: taskkill /PID %PID%
  - cmd: cd ..
  
os: Visual Studio 2015
before_build:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build_script:
  - cmd: bundle
  - cmd: bundle exec rake
test: off
version: 0.0.1.{build}
 